country_reverse = {
    'Bosnia and Herz.': ['Bosnia and Herzegovina', 'Bosnia & Herzegovina'],
    'Brunei': ['Brunei Darussalam'],
    'Central African Rep.': ['Central African Republic'],
    'Congo': ['Congo; R. of', 'Congo. R. of', 'Republic of Congo'],
    "Côte d'Ivoire": ["Cote d'Ivoire", "C̫te d'Ivoire", 'Ivory Coast'],
    'Cyprus': ['South Cyprus'],
    'Czechia': ['Czech Republic'],
    'Dem. Rep. Congo': ['Congo (ex-Zaire)', 'Democratic Republic of the Congo'],
    'Dominican Rep.': ['Dominican Republic'],
    'Eq. Guinea': ['Equatorial Guinea'],
    'eSwatini': ['Swaziland'],
    'Serbia': ['Republic of Serbia'],
    'Laos': ["Lao People's Democratic Republic"],
    'Moldova': ['Moldova, Republic of'],
    'N. Cyprus': ['North Cyprus', 'Northern Cyprus'],
    'North Korea': ['Korea (North)'],
    'Puerto Rico': ['Puerto Rico (USA)'],
    "Russia": ['Russia (Kaliningrad)', 'Russia (St Petersburg)', 'Russian Federation'],
    'South Korea': ['Korea (South)'],
    'S. Sudan': ['South Sudan'],
    'Syria': ['Syrian Arab Republic'],
    'Tanzania': ['United Republic of Tanzania'],
    'Timor-Leste': ['Timor Leste', 'East Timor'],
    'United States of America': ['US', 'United States', 'USA'],
    'Vietnam': ['Viet Nam'],
    'W. Sahara': ['Western Sahara (Morocco)', 'Western Sahara'],
    None: ['American Samoa', 'Andorra', 'Anguilla (UK)', 'Antigua and Barbuda',
           'Antigua & Barbuda',
           'Alaska (USA)',
           'Aruba (Netherlands)', 'Ascension Isl. (UK)', 'Azores Isl. (Portugal)','The Bahamas',
           'Bahrain', 'Barbados', 'Bermuda (UK)', 'Bonaire (Netherlands)',
           'Bouvet Isl.', 'Brit. Indian Ocean Terr. (UK)',
           'British Virgin Isl. (UK)', 'Cabo Verde', 'Cape Verde', 'Cayman Isl. (UK)', 'Channel Isl. (UK)',
           'Christmas Isl. (Australia)',
           'Cocos (Keeling) Isl. (Australia)', 'Comoros', 'Cook Islands',
           'Crozet Isl. (France)',
           'Curacao',
           'Dominica', 'European Union', 'Faeroe Isl. (Denmark)', 'Falkland Isl. (UK)',
           'French Polynesia',
           'French South Territories',
           'Gaza Strip', 'Gibraltar (UK)', 'Grenada', 'Guadeloupe (France)', 'Guadeloupe  (France)',
           'Guam (USA)', 'Guinea Bissau',
           'Heard Isl. And McDonald Isl.', 'Holy See', 'Hong Kong', 'Kerguelen Isl. (France)',
           'Isle of Man (UK)', 'Jan Maven', 'Johnson Atoll (USA)', 'Kiribati', 'Liechtenstein',
           'Macau', 'Madeira Isl. (Portugal)', 'Maldives', 'Malta', 'Marshall Isl.',
           'Martinique (France)', 'Micronesia',
           'Monaco', 'Montserrat (UK)', 'Mauritius',
           'Mayotte (France)', 'Nauru', 'Netherlands Antilles', 'New Caledonia (France)',
           'Niue (New Zealand)', 'Norfolk Isl. (Australia)', 'North Marianas (USA)',
           'Palau', 'Pitcairn (UK)', 'Réunion (France)', 'Reunion (France)',
           'Saba and Saint Eustaius (Netherlands)', 'Saint Helena (UK)',
           'Saint Kitts & Nevis', 'Saint Lucia',
           'Saint Pierre & Miquelon (France)', 'Saint Vincent & the Grenadines', 'Samoa', 'San Marino',
           'Sao Tome & Principe', 'Seychelles', 'Singapore', 'Sint Maarten',
           'Solomon Isl.', 'Solomon Islands', 'South Georgia and the South Sandwich Isl.',
           'St Barthelemy (France)', 'Svalbard Isl. (Norway)',
           'St Martin', 'Tokelau (New Zealand)', 'Tonga', 'Trinidad & Tobago', 'Tristan da Cunha Isl. (UK)',
           'Turks & Caicos Isl. (UK)',
           'Tuvalu',
           'US Virgin Isl.', 'Wallis and Futuna Isl. (France)', 'Wallis & Futuna Isl. (France)',
           'Yugoslavia',
           'nan'],

}

country_reference = {}
for c in country_reverse:
    for ci in country_reverse[c]:
        country_reference[ci] = c
